### PR TITLE
feat(travis): provide initial yml file

### PR DESCRIPTION
**Pull request by jaylenw**
### What does this PR do?

Adds initial travis integration. Travis will have docker-compose build and run the containers. If all is well, it passes, if a build fails, returns a non-zero exit code.

### Background info

This will be the basis of our travis file for now. We are aware a lot of work has to be done. For example, integrating unit tests and continuous deployment.

### CODE REVIEW

**Review by cheriejw — APPROVED** [review]
Nice, thank you for cleaning up that `README` 👍 Nice helpful comments in yml file!

**Comment by cheriejw** [comment]
NICE! Passing builds! Feel free to merge when you are ready! We will have an update meeting once I get back to nor cal (and holiday stuff calms down), and this may be a part of yours. :) #doingWORK

**Comment by cheriejw** [comment]
Oh also I usually put assignees as the people that worked on the PR (so you would have been the assignee); idk what you do, but I'm guessing it's so those people know they are assigned to CR this PR? But I just felt like it was repetitive since were already notified when you request us for review.

Doesn't matter though, but just thought I'd comment!

**Comment by RichCherng** [comment]
Are we using Travis for sure? Or Jenkins?

**Comment by jaylenw** [comment]
@RichCherng for now travis. Easier to setup at this point. I want to use Jenkins but i have to play around with it.

**Pull request merged**
